version: "2.1"
services:
<<<<<<< HEAD
  webtop:
    build: .
    # image: magicjf/anki-tiddlyremember:latest
    container_name: webtop
=======
  webtop-manual:
    build: .
    container_name: webtop-manual
>>>>>>> d5471faaae20655df02926e9f5104c8eae7f3bec
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
<<<<<<< HEAD
      - 3003:3000
      # - 3001:3001
      - 4000:8080
    shm_size: "2gb"
    restart: unless-stopped
    # volumes:
    #   - /home/joan/Documents/Github/Dockerizer/Webtop/jf-webtop/data:/config/app
      # - /data/apps/anki/config:/config/app
=======
      - 3033:3000
    shm_size: "2gb"
    restart: unless-stopped
    # volumes:
    #   - /data/apps/anki/config:/config/app
>>>>>>> d5471faaae20655df02926e9f5104c8eae7f3bec
