version: "2.1"
services:
  webtop-manual:
    build: .
    container_name: webtop-manual
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
      - 3033:3000
    shm_size: "2gb"
    restart: unless-stopped
    # volumes:
    #   - /data/apps/anki/config:/config/app