version: "2.1"
services:
  webtop:
    # build: .
    image: magicjf/anki-tiddlyremember:latest
    container_name: webtop
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/joan/Documents/Github/Dockerizer/Webtop/jf-webtop/data:/config
    ports:
      - 3000:3000
      - 3001:3001
      - 4000:8080
    shm_size: "2gb"
    restart: unless-stopped